title: Resultado Tech
header: Criando soluções através da tecnologia
subtitle: Tecnologia, engenharia de software, segurança da informação, e muito mais
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://resultadotech.com.br"

# Build settings
markdown: kramdown
permalink: blog/:title

paginate: 14
paginate_path: '/blog/:num/'

include: ['_pages']

# Pages Path
# defaults:
#  - scope:
#      path: '_pages'
#    values:
#      permalink: /:basename:output_ext

defaults:
  -
    scope:
      path:            "assets/*"
    values:
      sitemap:         false

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty



sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll/tagging

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
